name: Terraform CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.tf"
      - ".tflint.hcl"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1.EC2

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::151963020978:role/github-actions-terraform-ci
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: |
          tflint --init --config=${{ github.workspace }}/.tflint.hcl
          tflint --config=${{ github.workspace }}/.tflint.hcl

      - run: terraform plan -no-color
